<<<<<<< HEAD
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: products-service
  description: This is the products service
spec:
  type: service
  lifecycle: production
  owner: guests
=======
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp_project
  annotations:
    github.com/project-slug: patel0ankur/idp_project
spec:
  type: other
  lifecycle: unknown
  owner: guests
>>>>>>> 56cf2121b4048b78280f036f47013ac58b819864
