apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws-s3
  namespace: crossplane-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::590443650088:role/CrossplaneS3ProviderRole
