apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xobjectstorages.aws.example.com
spec:
  scope: Cluster
  group: aws.example.com
  names:
    kind: XObjectStorage
    plural: xobjectstorages
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  description: Name of the S3 bucket
                  type: string
                region:
                  description: AWS region for the bucket
                  type: string
                  default: us-east-1
              required:
                - bucketName
            status:
              type: object
              properties:
                bucketArn:
                  description: ARN of the created bucket
                  type: string
